### ISSUE TITLE
examples on other HAL crates

### ISSUE THREAD

**Issue by pdgilbert** [eldruin/driver-examples#3]
Thank you @eldruin  for your work on the device crates. As a novice I also very much appreciate your examples. Learning Rust I have been working through many examples and it is really nice to find well document ones that do not require out of date crates.

While you are well ahead of me in almost all respects, I have found a small innovation to organize example code that I have worked on with different HALs, and I hope you may find it interesting. The innovation is simply to organize the HAL/hardware specific code into a setup() function and return the objects used for the application. This allows the actual application code to be generic. Doing this I can build most of your bluepill examples using boards bluepill (stm32f103), discovery-stm32f303 , blackpill-stm32f401, blackpill-stm32f411, and some others. 22 of 25 examples I have tried are building.

The main complication of the setup functions is that the return type needs to be specified. This is greatly simplified if `impl trait` can be used. For many of your examples I need to return only `i2c`, `led`, and `delay`. Based on work I had already done it was mostly a simple copy and paste operation to get these working. I am having trouble with examples `ad9833-midi-player`, `si4703-fm-radio-display`, `si4703-fm-radio`, `iaq-core-c-gas-voc-usart-logger`, and `ccs811-gas-voc-usart-logger` as follows:

- for `ad9833-midi-player` I need a trait for the object returned by `Ad983x::new_ad9833(spi, cs)`. At least, this seems preferred based on other `spi` examples I have worked with. If there is a trait for this then I have not found it.

- for `si4703-fm-radio-display` and `si4703-fm-radio`  the type mismatch / trait problems reported in #2 has me stuck.

- `iaq-core-c-gas-voc-usart-logger-bp` and `ccs811-gas-voc-usart-logger-bp` have no entry point and call external C code. I do not understand this and have not attempted these examples.

I have also made these small changes:

- my workflow CI uses `build` with `example xxx` for each example `xxx`. I have never had luck with just building `examples`. I don't see how it can actual build the examples because it does not require setting a feature for the MCU, so I think it just does some general checks.

- blink is converted to be a method for an LED trait. This also looks after `on` being high with some hardware and low with other hardware.

- in `max30102-heart-usart` the `writeln!(tx, ...)`  is converted to `block!(tx.write(... ))` and `u32` to `u8`. This is because `writeln!` is not supported by all HAL crates. I am not sure if `u8` vs `u32` is a problem.

- I have been working with an object for the radio controls as reported in #2.

Also,
- I am using github versions of many crates because of changing naming conventions (eg `pac` vs `stm32`) and some release versions being a bit old.

- I do not yet have hardware to run much of this, it is only build tested.

- `RUSTFLAGS: '-D warnings'` stops the CI on warning, which prevents testing any following examples, so I have removed it. Warnings do get reported in the workflow artifacts.

- I'm not sure if your scripts are used in ci-rpi and microbit testing, I think they may be mostly left over from Travis. I am not using them.

- I'm not sure if `DRIVERS` are used in ci-rpi and microbit testing. I have not removed it but am not using it.

I have used HALS `stm32f0xx`, `stm32f1xx`, `stm32f3xx`, `stm32f4xx`, `stm32h7xx`, `stm32l0xx`, `stm32l1xx`, and `stm32l4xx`. All are working except `stm32f0xx` and `stm32l0xx` which are reporting 
```
error[E0599]: no method named `compare_exchange` found for reference `&AtomicBool` in the current scope
   --> /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/shared-bus-rtic-0.2.2/src/lib.rs:189:16
    |
189 |         atomic.compare_exchange(current, new, success, failure)
    |                ^^^^^^^^^^^^^^^^ method not found in `&AtomicBool`

error: aborting due to previous error
```

The code is at https://github.com/pdgilbert/driver-examples branch `generic-bare-metal`, and the CI is at https://github.com/pdgilbert/driver-examples/actions. It is still work in progress so the most recent workflow results may not be the most representative.

If there is interest in this I will work it into a PR when I have remaining examples working.

**Comment by eldruin** [comment]
Hi @pdgilbert, thank you for the kind words and your interesting work.
Some of the examples here definitely need a revamp, and I should update the f3 examples to use the up-to-date stm32f3-discovery crate and also cargo-embed there. However, I have not done it yet because I want to wire up an example and test that they continue to actually work after the update and for that I have not found the time.

My main goal in this repository is to offer simple, self-contained examples. The idea being that you can copy the whole file and it just works. No hidden magic.
One disadvantage I see in your current code is that the setup code is necessarily many times longer and a newcomer would need to understand that he/she only needs to look at a certain portion and then the generic code. But they can still feel overwhelmed by so much code and that would be a counter-goal for me.

However, I appreciate the idea of having generic code and building the examples against many other HALs/BSPs. Furthermore, it highlights certain problems like the lack of traits and so on, so I think it would be interesting to incorporate a new folder similar to yours.

While that is true, I think it would take me far too long to review and polish all your work in one go.
If that would be ok with you, I would like to start a new generic folder myself and pick setup code from your branch little by little as required and see how far that takes me.

Regarding the `iaq-core-c-gas-voc-usart-logger-bp` and `ccs811-gas-voc-usart-logger-bp` examples, they are based on the [RTIC](https://rtic.rs) framework (still all Rust) but they are a bit more difficult to adapt. I think they are not really useful, though.

The `compare_exchange` errors you are seeing on the `stm32f0xx` and `stm32l0xx` targets are due to the ARM-Cortex-M0 architecture not providing [CAS](https://en.wikipedia.org/wiki/Compare-and-swap). You can probably solve that by using a `NullMutex` from `shared-bus`, since all examples other than the RTIC-based ones do not have any kind of concurrency.

**Comment by pdgilbert** [comment]
I understand your concern about about the example code length with `setup()` functions and the problem that it makes a simple example more obscure. Please feel free to use whatever parts you want. Do note that in the branch of my fork the Cargo.toml is indicating github versions of many things, which is probably not what you want for a stable set of examples. Also, the `README.md` is modified to indicate shell variable settings for compiling.

My original motivation for the `setup()` functions was because I did not want to be committed to particular hardware and it helped me understand to what extent I was doing that. An added benefit seems to be that it highlights certain problems with both device crates and HAL crates. In this respect it might be thought of more like integration testing than like simple examples.

WRT "pick setup code from your branch little by little", 22 of the examples are almost identical. The exceptions are all mentioned above. It would be nice if the setup code could be maintained in a single copy but I have not figured out how to do it nicely. I can do it by putting it in src/ and that works well for bin code, but really obscures an example.

Thanks for your pointers on RTIC and CAS.

**Comment by pdgilbert** [comment]
(some updates)
Regarding
```
-for `ad9833-midi-player` I need a trait for the object returned by 
Ad983x::new_ad9833(spi, cs).  At least, this seems preferred based on 
other spi examples I have worked with. If there is a trait for this then 
I have not found it.
```
On rethinking, I suspect tying the `spi` into an object will interfere with using another channel on the `spi` for something else, and is not a good idea. So I adjusted my `setup()` to return the `spi` and `cs` separately. The revised version is in the `generic-bare-metal` branch of my fork. For the `bluepill` `setup()` I have not figured out the recipe for impl trait  for `spi`, it is using the specific type,  but I have impl traits  working for some other boards. Suggestions regarding `bluepill` appreciated.

Regarding `compare_exchange errors` and `CAS` I first fixed those simply by removing `shared-bus-rtic` and the  RTIC-based examples. I have not yet given up on the RTIC examples because I need to lean more about this for one of my eventual project. So instead I have now added an `optional` adjustment to use  `shared-bus-rtic` as needed in the `Cargo.toml`.

So, other than the RTIC examples the only ones not working now are `si4703-fm-radio-display` and `si4703-fm-radio` reported in #2.

My fork is still in place but I have also copied these examples with some others to https://github.com/pdgilbert/rust-integration-testing/. On that project I am testing the examples with both release and github version for various crates. It is easier to play with dependencies when not worrying about maintaining sanity on the fork.

**Comment by eldruin** [comment]
Sounds good. Thanks for the info.

**Comment by eldruin** [comment]
Hi @pdgilbert, I have been playing around with a generic-bare-metal version for a while and I think the amount of differences and boilerplate code for the different HALs is too much to be easily understandable (which is the purpose of this repository) and would be too difficult for me to maintain, so I would not include that in this repository.

However, your efforts are definitely valuable for the rust-embedded community and I would like to encourage you to go further into the path of interchangeability between HAL implementations and testing.

As such, I will go ahead and close this issue.
Thank you for your work!

**Comment by pdgilbert** [comment]
I understand that it confuses examples and also that this issue can be closed. BTW, there is a pretty big change in rtic 0.6.0, still in development. I have been playing with it because it allows the possibility of using setup() functions and running with different HALs.  There  is discussion at https://github.com/rtic-rs/cortex-m-rtic/issues/490 and https://github.com/rtic-rs/cortex-m-rtic/issues/523 and https://github.com/rtic-rs/cortex-m-rtic/issues/517. In addition to style and name changes there is better checking of the use of delay and systick. This came up when I was working on one of your examples, ccs811-gas-voc-usart-logger.rs I think. The delay while the sensor initialized conflicted with timing for spawning processes.

At https://github.com/pdgilbert/rust-integration-testing/tree/main/examples/driver-examples I have modifications of your two rtic examples building with dev versions. (At least building a few days ago, timing is always an issue with dev versions.) Please help yourself to anything useful. I don't have hardware to test these examples, so please let me know if you do test them.  Thanks for your help

**Comment by eldruin** [comment]
Cool stuff, thanks for the links!
